# Generated by Django 5.0.2 on 2025-08-21 06:23

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('mens', "Men's Wear"), ('kidsboys', 'Kids and Boys'), ('unisex', 'Unisex'), ('imported', 'Imported'), ('weddinghub', 'Wedding Suit')], max_length=32)),
                ('sub_category', models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Cotton Pant', 'Cotton Pant'), ('Footwear', 'Footwear'), ('Co-ords', 'Co-ords'), ('Watches', 'Watches'), ('Track', 'Track'), ('Caps', 'Caps'), ('Jewellery', 'Jewellery'), ('Sunglasses', 'Sunglasses'), ('Wallets', 'Wallets'), ('Combo set', 'Combo set'), ('Pants', 'Pants'), ('Shorts', 'Shorts'), ('Belt', 'Belt'), ('Suit', 'Suit'), ('Sherwani', 'Sherwani'), ('Watch', 'Watch'), ('Jacket', 'Jacket'), ('Perfume', 'Perfume'), ('Lotion', 'Lotion'), ('Crocs', 'Crocs'), ('Jodhpuri', 'Jodhpuri'), ('Kurthas', 'Kurthas'), ('Dress code', 'Dress code')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('weight', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_to_product)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
    ]
